cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js:
- '10'
- '12'
- '14'
deploy:
  provider: npm
  email: kelsin@valefor.com
  api_key:
    secure: G8KiI5uaitQQ778AeeotJxpQDdr/WZL4nj71sdSGpbbgciU9u9XEGHWn3QeCG6zItwExVdIAElJBG14wWZBLBIAdq5DDAYxCpN3sSnl5n9gpYgjLtSbo8VCM2nqweGImY+Qg+aDRMF8F7qnvgRlKjtc7wZVsXDkkHQcuBQXppAFBIlOWMzNxd5HQ5Q+LwtnT8ToyPqv3cff6+41GuiHbtS3m6dGEWSQe7XAXLm5gOoMA5U1cpvmgAhPgbOcuaEdQHkKuazzR9Cl4V8uyxtvf1Hu4wqSzYiN4OKSX1rIaj8uXqjDXUIT7q8MaXxs/bIrq+LA9PS4pC8s8lfRd7MIgaFc0iKtLGodkp4osYfUx/pAvMChtGNGuKokh7jk2Z+HLAkefM8r9gPuagffm/6bCLLE78WBCA64i3NbF9qe9+9hSdO3YIQLQ2Ih8tKJfXl+oNuuokD2q31bv17/ZGrG4fckTBAlLwmmmsIzKUvLAZ4I4r6TvRaCpxHAp1fFUd1vgQEWtN9QAjHBEGkscJHw9QXOwqzhuuHfUeqdM3p/O7Hx71q9bZTK6s+X+azgizEVJr1DbLmPhhgCva2HK5lPWvcbuTJYlE3f9MAuoPBqIhepOKBhwk2pgtzHe0Ri6sjXlDE1lfJiR9hoAAYbHSZi5Np4BxMGxisF+Nw+dL4sJ5tA=
  on:
    tags: true
    repo: 18xx-maker/export-rb
    node_js: '12'
  skip_cleanup: 'true'
